export const ActionTypes = {
  SET_PRODUCT: "SELECTED_PRODUCT",
  SET_CATEGORY_TITLE: "SET_CATEGORY_TITLE",
  SET_CURRENCY_TYPE: "SET_CURRENCY_TYPE",
  ADD_TO_CART: "ADD_TO_CART",
  DECREASE_FROM_CART: "DECREASE_FROM_CART",
}